Report listing pages localized [PIVOT-728]
THLfi/tiku pull request #51
Opened 2020-01-28 15:53 UTC by thl-juhovikman

Localized static content, report titles and links to reports

2020-01-28 19:02 UTC, thl-janimalminen requested changes
Muuten hyvä, mutta käyttäjältä tulevien parametrien tarkastukseen kannattaa kiinnittää huomiota. Esim AmorListController saa url parametrina kielen ja se tulostetaan edelleen freemarker templaatissa, jolloin xss-injektio voi olla mahdollinen.

2020-01-28 19:02 UTC, thl-janimalminen commented on src/main/java/fi/thl/pivot/web/AmorListController.java
>          model.addAttribute("showRestrictedView", true);
Lisäisin tähän kohtaan ainakin 'locale' parametrille jonkinlaisen validoinnin erilaisten injektioiden ehkäisemiseksi. Yksinkertaisimmillaan se voisi olla pituuden tarkastus, eli käytetään vaikka oletusarvoa 'fi' jos parametrin pituus on yli kaksi merkkiä. Tai regex joka sallii vain aakkoset.

2020-01-29 07:22 UTC, thl-juhovikman commented on src/main/java/fi/thl/pivot/web/AmorListController.java
>          model.addAttribute("showRestrictedView", true);
Juuri tuossa kohtaa olikin jo RequestMappingin rajoite {locale:[a-z][a-z]}, joten virheellinen syöte ei pääse lisäämääni validointiin asti. Toisaalta hydraan kuuluvien raporttien listauksessa tuota ei ollut. Lisäsin sinnekin saman.

2020-01-29 07:25 UTC, thl-janimalminen approved these changes
Totta, jäi huomaamatta että validointi olikin tehty jo Springin avulla.

2020-01-29 07:26 UTC, merged